// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/7/2026, 10:19:22
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/wamp64/www/BookOfPages/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/plugins/**/*.{js,ts,mjs}","C:/wamp64/www/BookOfPages/composables/**/*.{js,ts,mjs}","C:/wamp64/www/BookOfPages/utils/**/*.{js,ts,mjs}","C:/wamp64/www/BookOfPages/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/BookOfPages/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;