// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/9/2026, 16:39:18
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/wamp64/www/MonkeyvsBird/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/plugins/**/*.{js,ts,mjs}","C:/wamp64/www/MonkeyvsBird/composables/**/*.{js,ts,mjs}","C:/wamp64/www/MonkeyvsBird/utils/**/*.{js,ts,mjs}","C:/wamp64/www/MonkeyvsBird/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/MonkeyvsBird/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;